name: release deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore cache for Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configure app version
        id: config_version
        run: |
          echo ::set-output name=GLOBAL::$(cat ./_version.yml | grep -e '^global: [0-9]*\.[0-9]*\.[0-9]*$' | sed -e 's/global: //g')

      - name: Restore keystore and build project with Gradle
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ./sallyluenoa_sample.jks
          chmod +x gradlew
          ./gradlew assembleRelease publish --no-daemon -Pversion.name=${{ steps.config_version.outputs.GLOBAL }} -Pversion.code=$GITHUB_RUN_NUMBER

      - name: Build kdoc with Gradle and update docs
        run: |
          chmod +x gradlew
          ./gradlew dokkaHtml --no-daemon
          rm -fr ./docs/*
          cp -r ./frextensions/build/dokka/html/* ./docs
          sed -i -E "/^\s*<h1.*<\/h1>$/s/frextensions/FRExtensions v${{ steps.config_version.outputs.GLOBAL }}/g" ./docs/index.html
          sed -i -E "s/[0-9]*\.[0-9]*\.[0-9]*/${{ steps.config_version.outputs.GLOBAL }}/g" ./README.md

      - name: Archive artifacts
        run: |
          mkdir ./archive
          zip -r ./archive/release-build-artifacts.zip ./frextensions/build/outputs/aar/*.aar ./sample/build/outputs/apk/release/*.apk
          zip ./archive/release-kdoc-artifacts.zip ./docs

      - name: Add commit for update docs
        uses: EndBug/add-and-commit@v7
        with:
          add: "['./README.md', './docs']"
          message: "[RELEASE DEPLOY v${{ steps.config_version.outputs.GLOBAL }}] Update kdoc."

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.config_version.outputs.GLOBAL }}
          release_name: Release v${{ steps.config_version.outputs.GLOBAL }}
          commitish: master

      - name: Upload release asset for build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./archive/release-build-artifacts.zip
          asset_name: release-build-artifacts-v${{ steps.config_version.outputs.GLOBAL }}.zip
          asset_content_type: application/zip

      - name: Upload release asset for kdoc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./archive/release-kdoc-artifacts.zip
          asset_name: release-kdoc-artifacts-v${{ steps.config_version.outputs.GLOBAL }}.zip
          asset_content_type: application/zip
