name: sandbox build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Create new file
        run: |
          touch ./docs/index.md

      - name: Git settings
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit file
        run: |
          git pull
          git add ./docs/index.md
          git commit -am "Auto commit test."
          git push origin HEAD
