name: sandbox build

on:
  push:
    branches:
      - sandbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Configure version.
        id: config_version
        run: |
          echo ::set-output name=GLOBAL::$(cat ./_version.yml | grep -e '^global: \d+\.\d+\.\d+$' | sed -e 's/global: //g')

      - name: Test command.
        run: |
          cat ./_version.yml
          cat ./_version.yml | grep -e '^global: [0-9]+\.[0-9]+\.[0-9]+$'
          cat ./_version.yml | sed -e 's/global: //g'
          cat ./_version.yml | grep -e '^global: [0-9]+\.[0-9]+\.[0-9]+$' | sed -e 's/global: //g'
          echo ${{ steps.config_version.outputs.GLOBAL }}
